apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-vol-2
  name: nginx-2
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-vol-2
status:
  loadBalancer: {}
