apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-vol-2
  name: nginx-vol-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-vol-2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-vol-2
    spec:
      containers:
      - image: nginx-1.7.9
        name: nginx-1-7-9
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-vol
          mountPath: /vol
        resources: {}
      volumes:
      - name: nginx-vol
        hostPath:
          path: /data
          type: Directory
status: {}
