apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: store 
  name: 1stnode
spec:
  containers:
  - image: nginx
    name: 1stnode
    imagePullPolicy: IfNotPresent
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: 2ndnode
  name: 2ndnode
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - store
        topologyKey: kubernetes.io/hostname
  containers:
  - image: nginx
    name: 2ndnode
    imagePullPolicy: IfNotPresent
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

