apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: task-1
  name: task-1
spec:
  nodeSelector:
    disktype: SSD
  containers:
  - image: nginx
    name: task-1
    imagePullPolicy: IfNotPresent
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
