apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    client: user
    app: revproxy
  name: revproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: revproxy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: revproxy
    spec:
      containers:
      - image: nginx:1.7.9
        name: nginx
        resources: {}
status: {}
